# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Bump version and publish PYPI package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install poetry
      - name: Bump version, build and publish
        env:
          USERNAME: __token__
          PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
        run: |
          poetry version $VERSION
          poetry publish --build -u $USERNAME -p $PYPI_API_KEY
